#include "gui/gui.h"

gui_const uint8_t Font_Arial_Bold_18_0020[1] = {
    ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0021[13] = {
    XXXXX___, 
    XXXXX___, 
    XXXXX___, 
    XXXXX___, 
    _XXXX___, 
    _XXX____, 
    _XXX____, 
    _XXX____, 
    _XX_X___, 
    ________, 
    XXXXX___, 
    XXXXX___, 
    XXXXX___, 
};

gui_const uint8_t Font_Arial_Bold_18_0022[10] = {
    _XXXX_X_, _XXXX_X_, 
    _XXXX_X_, _XXXX_X_, 
    _XXXX_X_, _XXXX_X_, 
    _XXXX___, _X_XX_X_, 
    _X_XX___, __XXX___, 
};

gui_const uint8_t Font_Arial_Bold_18_0023[39] = {
    _______X, _XX_X__X, _XX_X___, 
    _______X, _XX____X, XXX_____, 
    _______X, XXX____X, XXX_____, 
    _X_XXXXX, XXXXXXXX, XXXX____, 
    _X_XXXXX, XXXXXXXX, XXXX____, 
    _____X_X, X_X__X_X, X_______, 
    _____XXX, X____XXX, X_______, 
    _____XXX, X____XXX, ________, 
    _X_XXXXX, XXXXXXXX, XXXX____, 
    _X_XXXXX, XXXXXXXX, XXXX____, 
    ___X_XX_, ___X_XX_, ________, 
    ___XXXX_, ___XXXX_, ________, 
    ___XXX__, ___XXX__, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0024[48] = {
    ________, XX______, ________, 
    ____XX_X, XXXXX_X_, ________, 
    __XXXXXX, XXXXXXX_, X_______, 
    _XXXXX__, XX__XXXX, ________, 
    _XXXX___, XX______, ________, 
    _XXXXX__, XX______, ________, 
    __XXXXXX, XXX_X___, ________, 
    ____XXXX, XXXXXXX_, ________, 
    _______X, _XXXXXXX, X_______, 
    ________, XX___XXX, X_______, 
    _XXXX_X_, XX___XXX, X_______, 
    _XXXXX__, XX__XXXX, X_______, 
    __XXXXXX, XXXXXXX_, X_______, 
    ____XX_X, XXXX__X_, ________, 
    ________, XX______, ________, 
    ________, XX______, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0025[56] = {
    __XXXXXX, X_X_____, ___XXX__, ________, 
    _XXX___X, XXX_____, __XXX___, ________, 
    _XXX___X, _XX_____, _XXX____, ________, 
    _XXX___X, _XX_____, XXX_X___, ________, 
    _XXX___X, _XX____X, XXX_____, ________, 
    __XXXXXX, X_X___XX, X_X_____, ________, 
    ________, _____XXX, X_______, ________, 
    ________, ____XXX_, X_______, ________, 
    ________, ___XXXX_, ___X_XXX, X_X_____, 
    ________, __XXX_X_, __XXX_X_, XXX_X___, 
    ________, _X_XX___, _X_XX___, _XXX____, 
    ________, _XX_X___, _X_XX___, _XXX____, 
    _______X, _XX_____, __XXX_X_, XXX_X___, 
    _______X, XX______, ___X_XXX, X_X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0026[52] = {
    ______XX, XXXXXX__, ________, ________, 
    ____XXXX, XXXXXXXX, X_______, ________, 
    ___X_XXX, X____XXX, X_X_____, ________, 
    ___X_XXX, X____XXX, X_X_____, ________, 
    _____XXX, XX_X_XXX, X_______, ________, 
    _____X_X, XXXXXX__, ________, ________, 
    ___X_XXX, XXXXX_X_, ________, ________, 
    _X_XXXX_, XX_XXXX_, XX_XX_X_, ________, 
    _XXXX_X_, ___X_XXX, XXXXX_X_, ________, 
    _XXXX___, _____XXX, XXXXX___, ________, 
    _XXXXX__, ____XXXX, XXXXX_X_, ________, 
    __XXXXXX, XXXXXXXX, XXXXXXX_, X_______, 
    ____XX_X, XXXXXX__, ___X_X__, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0027[5] = {
    _XXXX___, 
    _XXXX___, 
    _XXXX___, 
    _XXXX___, 
    _X_XX___, 
};

gui_const uint8_t Font_Arial_Bold_18_0028[34] = {
    _____XXX, X_______, 
    ____XXXX, ________, 
    ___XXXX_, X_______, 
    __XXXXX_, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _X_XXX__, ________, 
    __XXXX__, ________, 
    __XXXXX_, ________, 
    ___XXXX_, X_______, 
    ____XXXX, ________, 
    _____XXX, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0029[34] = {
    _XXXX___, ________, 
    _X_XX_X_, ________, 
    __XXXXX_, ________, 
    ___XXXX_, X_______, 
    ___X_XXX, ________, 
    ____XXXX, ________, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ___X_XXX, ________, 
    ___X_XX_, X_______, 
    ___XXXX_, X_______, 
    __XXXXX_, ________, 
    _X_XX_X_, ________, 
    _XXXX___, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_002a[12] = {
    ______XX, X_______, 
    __X_X_XX, X_XX____, 
    _X_XXXXX, XXXXX_X_, 
    _____XXX, XX______, 
    ____XXX_, XXX_____, 
    ___X__X_, _X__X___, 
};

gui_const uint8_t Font_Arial_Bold_18_002b[27] = {
    _______X, XXX_X___, ________, 
    _______X, XXX_X___, ________, 
    _______X, XXX_X___, ________, 
    _XXXXXXX, XXXXXXXX, XX______, 
    _XXXXXXX, XXXXXXXX, XX______, 
    _XXXXXXX, XXXXXXXX, XX______, 
    _______X, XXX_X___, ________, 
    _______X, XXX_X___, ________, 
    _______X, XXX_X___, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_002c[6] = {
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    ____XX__, 
    ___XX_X_, 
    _X__X___, 
};

gui_const uint8_t Font_Arial_Bold_18_002d[6] = {
    _XXXXXXX, XX______, 
    _XXXXXXX, XX______, 
    _XXXXXXX, XX______, 
};

gui_const uint8_t Font_Arial_Bold_18_002e[3] = {
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
};

gui_const uint8_t Font_Arial_Bold_18_002f[26] = {
    _______X, XX______, 
    _______X, X_X_____, 
    ______XX, X_X_____, 
    _____X_X, X_______, 
    _____XXX, X_______, 
    _____XXX, ________, 
    ____XXX_, X_______, 
    ___X_XX_, ________, 
    ___XXXX_, ________, 
    ___XXX__, ________, 
    __XXX_X_, ________, 
    _X_XX___, ________, 
    _XXXX___, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0030[39] = {
    _____X_X, XXXX____, ________, 
    ___XXXXX, XXXXXXX_, ________, 
    _X_XXXX_, ___XXXXX, ________, 
    _XXXX_X_, ____XXXX, X_______, 
    _XXXX___, ____XXXX, X_______, 
    _XXXX___, _____XXX, X_______, 
    _XXXX___, _____XXX, X_______, 
    _XXXX___, _____XXX, X_______, 
    _XXXX___, ____XXXX, X_______, 
    _XXXX_X_, ____XXXX, X_______, 
    _X_XXXX_, ___XXXXX, ________, 
    ___XXXXX, XXXXXXX_, ________, 
    _____X_X, XXXX____, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0031[26] = {
    _______X, XXX_____, 
    _____X_X, XXX_____, 
    __XXXXXX, XXX_____, 
    XXXXXXXX, XXX_____, 
    XXXX__XX, XXX_____, 
    X_X___XX, XXX_____, 
    ______XX, XXX_____, 
    ______XX, XXX_____, 
    ______XX, XXX_____, 
    ______XX, XXX_____, 
    ______XX, XXX_____, 
    ______XX, XXX_____, 
    ______XX, XXX_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0032[39] = {
    ____XX_X, XXXX__X_, ________, 
    __XXXXXX, XXXXXXX_, X_______, 
    _XXXXX__, ___X_XXX, X_______, 
    _X_XX___, ____XXXX, X_______, 
    ________, ____XXXX, X_______, 
    ________, ___XXXXX, X_______, 
    ________, _X_XXXX_, X_______, 
    _______X, XXXXX_X_, ________, 
    _____XXX, XXXX____, ________, 
    ___XXXXX, X_X_____, ________, 
    _X_XXXX_, X_______, ________, 
    _XXXXXXX, XXXXXXXX, X_______, 
    XXXXXXXX, XXXXXXXX, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0033[39] = {
    _____X_X, XXXX____, ________, 
    ___XXXXX, XXXXXXX_, ________, 
    _X_XXXX_, ___XXXX_, X_______, 
    _X_X__X_, ___XXXX_, X_______, 
    ________, __XXXXX_, X_______, 
    _______X, _XXXX_X_, ________, 
    _______X, _XXXXX__, ________, 
    ________, ___X_XXX, ________, 
    ________, ____XXXX, X_______, 
    _X_XX_X_, ____XXXX, X_______, 
    _XXXXX__, ___X_XXX, X_______, 
    __XXXXXX, XXXXXXX_, X_______, 
    ____XX_X, XXXX____, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0034[39] = {
    ________, ____XXXX, X_______, 
    ________, ___XXXXX, X_______, 
    ________, _XXXXXXX, X_______, 
    ________, XXXXXXXX, X_______, 
    ______XX, XXX_XXXX, X_______, 
    _____XXX, X_X_XXXX, X_______, 
    ___X_XXX, ____XXXX, X_______, 
    __XXXXX_, ____XXXX, X_______, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    ________, ____XXXX, X_______, 
    ________, ____XXXX, X_______, 
    ________, ____XXXX, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0035[39] = {
    ___X_XXX, XXXXXXXX, ________, 
    ___XXXXX, XXXXXXXX, ________, 
    ___XXXX_, ________, ________, 
    __XXXXX_, ________, ________, 
    __XXXXXX, XXXXX_X_, ________, 
    _X_XXXXX, XXXXXXX_, X_______, 
    _X_XXX__, ___X_XXX, X_______, 
    ________, _____XXX, X_______, 
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_______, 
    _XXXXX__, ___X_XXX, X_______, 
    _X_XXXXX, XXXXXXX_, ________, 
    ____XX_X, XXXX____, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0036[39] = {
    _____X_X, XXXXX_X_, ________, 
    ___X_XXX, XXXXXXX_, X_______, 
    __XXXXX_, ___X_XXX, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_XX, _XXXX_X_, ________, 
    _XXXXXXX, XXXXXXX_, X_______, 
    _XXXXXX_, ___X_XXX, X_______, 
    _XXXX_X_, ____XXXX, X_______, 
    _XXXX_X_, _____XXX, X_______, 
    _XXXXX__, ____XXXX, X_______, 
    _X_XXXX_, ___X_XXX, ________, 
    ___XXXXX, XXXXXXX_, ________, 
    _____X_X, XXXX____, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0037[39] = {
    _XXXXXXX, XXXXXXXX, X_______, 
    _XXXXXXX, XXXXXXXX, X_______, 
    ________, ___XXXXX, ________, 
    ________, _X_XXXX_, ________, 
    ________, _XXXX_X_, ________, 
    _______X, _XXX____, ________, 
    _______X, XXX_X___, ________, 
    _____X_X, XXX_____, ________, 
    _____XXX, XX______, ________, 
    _____XXX, X_X_____, ________, 
    ____XXXX, X_______, ________, 
    ____XXXX, X_______, ________, 
    ____XXXX, X_______, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0038[39] = {
    ____XX_X, XXXX__X_, ________, 
    __XXXXXX, XXXXXXX_, X_______, 
    _XXXXX__, ___XXXXX, ________, 
    _XXXX_X_, ____XXXX, X_______, 
    _X_XXX__, ___XXXXX, ________, 
    ___X_XXX, XXXXXX__, ________, 
    ___X_XXX, XXXXXX__, ________, 
    _X_XXX__, ___X_XXX, ________, 
    _XXXX_X_, ____XXXX, X_______, 
    _XXXX_X_, ____XXXX, X_______, 
    _XXXXX__, ___X_XXX, X_______, 
    __XXXXXX, XXXXXXX_, X_______, 
    ____XX_X, XXXX__X_, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0039[39] = {
    ____XX_X, XXXX____, ________, 
    __XXXXXX, XXXXXX__, ________, 
    _XXXXX__, __XXXXX_, X_______, 
    _XXXX_X_, ___X_XXX, X_______, 
    _XXXX___, ____XXXX, X_______, 
    _XXXX_X_, ___X_XXX, X_______, 
    _XXXXX__, ___XXXXX, X_______, 
    __XXXXXX, XXXXXXXX, X_______, 
    ____XXXX, XX_X_XXX, X_______, 
    ________, ____XXXX, X_______, 
    _X_XXX__, ___XXXX_, X_______, 
    __XXXXXX, XXXXXX__, ________, 
    ____XXXX, XXX_X___, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_003a[10] = {
    _XXXX___, 
    _XXXX___, 
    _XXXX___, 
    ________, 
    ________, 
    ________, 
    ________, 
    _XXXX___, 
    _XXXX___, 
    _XXXX___, 
};

gui_const uint8_t Font_Arial_Bold_18_003b[13] = {
    _XXXX___, 
    _XXXX___, 
    _XXXX___, 
    ________, 
    ________, 
    ________, 
    ________, 
    _XXXX___, 
    _XXXX___, 
    _XXXX___, 
    ___XX___, 
    _X_X____, 
    _X______, 
};

gui_const uint8_t Font_Arial_Bold_18_003c[30] = {
    ________, ________, X_X_____, 
    ________, ___X_XXX, X_X_____, 
    ______XX, _XXXXXXX, X_X_____, 
    __XXXXXX, XXXXXX__, X_______, 
    _XXXXXX_, X_X_____, ________, 
    _XXXXXXX, __X_____, ________, 
    __XXXXXX, XXXXXX__, X_______, 
    ______XX, _XXXXXXX, X_X_____, 
    ________, ___X_XXX, X_X_____, 
    ________, ________, X_X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_003d[24] = {
    _XXXXXXX, XXXXXXXX, XX______, 
    _XXXXXXX, XXXXXXXX, XX______, 
    _XXXXXXX, XXXXXXXX, XX______, 
    ________, ________, ________, 
    ________, ________, ________, 
    _XXXXXXX, XXXXXXXX, XX______, 
    _XXXXXXX, XXXXXXXX, XX______, 
    _XXXXXXX, XXXXXXXX, XX______, 
};

gui_const uint8_t Font_Arial_Bold_18_003e[30] = {
    _X______, ________, ________, 
    _XXXXX__, X_______, ________, 
    _XXXXXXX, XXX_X___, ________, 
    ____XXXX, XXXXXXX_, X_______, 
    ________, __XX_XXX, X_X_____, 
    ________, __XXXXXX, X_X_____, 
    ____XXXX, XXXXXXX_, X_______, 
    _XXXXXXX, XXX_X___, ________, 
    _XXXXX__, X_______, ________, 
    _X______, ________, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_003f[39] = {
    _____X_X, XXXXXX__, ________, 
    ___XXXXX, XXXXXXXX, X_X_____, 
    _X_XXXX_, X____X_X, XXX_____, 
    _XXXXX__, _______X, XXX_____, 
    ________, _____X_X, XXX_____, 
    ________, ___X_XXX, X_X_____, 
    ________, _XXXXXX_, ________, 
    ________, XXXXX___, ________, 
    _______X, _XXX____, ________, 
    ________, ________, ________, 
    _______X, _XXX____, ________, 
    _______X, _XXX____, ________, 
    _______X, _XXX____, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0040[85] = {
    ________, ____XX_X, XXXXXX__, X_______, ________, 
    _______X, _XXXXXXX, XXXXXXXX, XXX_X___, ________, 
    _____X_X, XXX_X___, ________, XXXXX_X_, ________, 
    ___X_XXX, ____XXXX, XXX__XXX, X_XXXXX_, ________, 
    __XXXX__, __XXXXXX, XXXXXXXX, X____XX_, X_______, 
    _X_XX___, _XXXXX__, ___XXXXX, X____XXX, ________, 
    _XXX___X, _XXX____, ___X_XXX, _____X_X, X_______, 
    XXX_X__X, XXX_X___, ___X_XX_, X____X_X, X_______, 
    XXX____X, XXX_____, ___XXXX_, _____XXX, ________, 
    XXX____X, XXX_____, ___XXXX_, ___X_XX_, X_______, 
    _XX_X__X, XXXX____, _X_XXXX_, _X_XXX__, ________, 
    _XXX____, XXXXXXXX, XXXXXXXX, XXXX____, ________, 
    _X_XX_X_, __XXXXXX, ___XXXXX, X_X_____, ________, 
    ___XXXX_, X_______, ________, _____XXX, X_______, 
    ____XXXX, XX__X___, ________, XX_XXXX_, X_______, 
    ______XX, XXXXXXXX, XXXXXXXX, XXXXX_X_, ________, 
    ________, __XX_X_X, XXXXXXXX, __X_____, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0041[52] = {
    ________, __XXXXXX, ________, ________, 
    ________, _X_XXXXX, X_______, ________, 
    ________, _XXXXXXX, X_X_____, ________, 
    ________, XXXXXX_X, XXX_____, ________, 
    _______X, _XXX___X, XXX_X___, ________, 
    _______X, XXX_X__X, _XXX____, ________, 
    ______XX, XXX_____, XXXXX___, ________, 
    _____XXX, XXXXXXXX, XXXXX_X_, ________, 
    ____XXXX, XXXXXXXX, XXXXXXX_, ________, 
    ___X_XXX, XXXXXXXX, XXXXXXX_, X_______, 
    ___XXXXX, ________, ___XXXXX, ________, 
    __XXXXX_, X_______, ___X_XXX, X_______, 
    _X_XXXX_, ________, ____XXXX, X_X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0042[39] = {
    _X_XXXXX, XXXXXXXX, XX______, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXXXX, XXXXXXXX, XXXXX_X_, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXXXX, XXXXXXXX, XXXX____, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, XXXXX_X_, 
    _X_XXX__, ________, _X_XXXX_, 
    _X_XXX__, ________, _X_XXXX_, 
    _X_XXXXX, XXXXXXXX, XXXXXXX_, 
    _X_XXXXX, XXXXXXXX, XXXXX_X_, 
    _X_XXXXX, XXXXXXXX, XX__X___, 
};

gui_const uint8_t Font_Arial_Bold_18_0043[39] = {
    _______X, _XXXXXXX, __X_____, 
    ____XXXX, XXXXXXXX, XXXX____, 
    ___XXXXX, XXXXXXXX, XXXXX_X_, 
    _X_XXXXX, ________, XXXXXXX_, 
    _XXXXX__, ________, _X_X____, 
    _XXXX_X_, ________, ________, 
    _XXXX___, ________, ________, 
    _XXXX_X_, ________, ________, 
    _XXXXX__, ________, _X_X____, 
    _X_XXXXX, ________, XXXXXXX_, 
    ___XXXXX, XXXXXXXX, XXXXX_X_, 
    ____XXXX, XXXXXXXX, XXXX____, 
    _______X, _XXXXXXX, __X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0044[39] = {
    _X_XXXXX, XXXXXXXX, __X_____, 
    _X_XXXXX, XXXXXXXX, XXXX____, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXX__, ________, XXXXXX__, 
    _X_XXX__, ________, _X_XXXX_, 
    _X_XXX__, ________, __XXXXX_, 
    _X_XXX__, ________, ___XXXX_, 
    _X_XXX__, ________, __XXXXX_, 
    _X_XXX__, ________, _X_XXXX_, 
    _X_XXX__, ________, XXXXXX__, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXXXX, XXXXXXXX, XXXX____, 
    _X_XXXXX, XXXXXXXX, __X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0045[39] = {
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
};

gui_const uint8_t Font_Arial_Bold_18_0046[39] = {
    _X_XXXXX, XXXXXXXX, XXX_____, 
    _X_XXXXX, XXXXXXXX, XXX_____, 
    _X_XXXXX, XXXXXXXX, XXX_____, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXXXX, XXXXXXXX, X_______, 
    _X_XXXXX, XXXXXXXX, X_______, 
    _X_XXXXX, XXXXXXXX, X_______, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0047[52] = {
    ________, XX_XXXXX, XX______, ________, 
    _____XXX, XXXXXXXX, XXXXX_X_, ________, 
    ___XXXXX, XXXXXXXX, XXXXXXX_, ________, 
    _X_XXXXX, __X_____, _X_XXXX_, X_______, 
    _XXXXX__, ________, ___X__X_, ________, 
    _XXXX_X_, ________, ________, ________, 
    _XXXX___, _____X_X, XXXXXXXX, ________, 
    _XXXX_X_, _____X_X, XXXXXXXX, ________, 
    _XXXXXX_, _____X_X, XXXXXXXX, ________, 
    _X_XXXXX, __X_____, ___X_XXX, ________, 
    ___XXXXX, XXXXXXXX, XXXXXXX_, X_______, 
    _____XXX, XXXXXXXX, XXXXX_X_, ________, 
    ________, XX_XXXXX, XX______, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0048[39] = {
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXXXX, XXXXXXXX, XXXXXX__, 
    _X_XXXXX, XXXXXXXX, XXXXXX__, 
    _X_XXXXX, XXXXXXXX, XXXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
    _X_XXX__, ________, _XXXXX__, 
};

gui_const uint8_t Font_Arial_Bold_18_0049[13] = {
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
};

gui_const uint8_t Font_Arial_Bold_18_004a[39] = {
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_X_____, 
    ________, _____XXX, X_X_____, 
    _X_XXXX_, _____XXX, X_X_____, 
    __XXXXX_, X___XXXX, X_X_____, 
    __XXXXXX, XXXXXXXX, X_______, 
    ___X_XXX, XXXXXXXX, ________, 
    _____X_X, XXXXX_X_, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_004b[52] = {
    _X_XXXX_, ________, _XXXXXX_, ________, 
    _X_XXXX_, _______X, XXXXX___, ________, 
    _X_XXXX_, _____XXX, XXX_X___, ________, 
    _X_XXXX_, ___X_XXX, X_X_____, ________, 
    _X_XXXX_, _X_XXXX_, X_______, ________, 
    _X_XXXXX, _XXXXXX_, ________, ________, 
    _X_XXXXX, XXXXXXX_, X_______, ________, 
    _X_XXXXX, XX_X_XXX, X_______, ________, 
    _X_XXXXX, _____XXX, XX______, ________, 
    _X_XXXX_, _____X_X, XXX_X___, ________, 
    _X_XXXX_, _______X, XXXXX___, ________, 
    _X_XXXX_, ________, XXXXXXX_, ________, 
    _X_XXXX_, ________, _X_XXXX_, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_004c[39] = {
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXX_, ________, ________, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
};

gui_const uint8_t Font_Arial_Bold_18_004d[52] = {
    _XXXXXXX, X_______, ___XXXXX, XXX_____, 
    _XXXXXXX, X_X_____, __XXXXXX, XXX_____, 
    _XXXXXXX, XX______, _X_XXXXX, XXX_____, 
    _XXXXXXX, XXX_____, _XXXXX_X, XXX_____, 
    _XXXXX_X, XXX_X___, _XXXX_XX, XXX_____, 
    _XXXXX_X, _XX_X___, XXXX__XX, XXX_____, 
    _XXXXX__, XXXXX__X, _XX_X_XX, XXX_____, 
    _XXXXX__, _XXXX__X, XXX___XX, XXX_____, 
    _XXXXX__, _XXXXX_X, XXX___XX, XXX_____, 
    _XXXXX__, __XXXXXX, XX____XX, XXX_____, 
    _XXXXX__, __XXXXXX, X_X___XX, XXX_____, 
    _XXXXX__, ___XXXXX, X_____XX, XXX_____, 
    _XXXXX__, ___X_XXX, ______XX, XXX_____, 
};

gui_const uint8_t Font_Arial_Bold_18_004e[39] = {
    _X_XXXX_, ________, _XXXX_X_, 
    _X_XXXXX, X_______, _XXXX_X_, 
    _X_XXXXX, X_X_____, _XXXX_X_, 
    _X_XXXXX, XXX_____, _XXXX_X_, 
    _X_XXXXX, XXXX____, _XXXX_X_, 
    _X_XXXX_, XXXXX___, _XXXX_X_, 
    _X_XXXX_, _XXXXX__, _XXXX_X_, 
    _X_XXXX_, __XXXXX_, XXXXX_X_, 
    _X_XXXX_, ___X_XXX, XXXXX_X_, 
    _X_XXXX_, _____XXX, XXXXX_X_, 
    _X_XXXX_, _____X_X, XXXXX_X_, 
    _X_XXXX_, _______X, XXXXX_X_, 
    _X_XXXX_, ________, XXXXX_X_, 
};

gui_const uint8_t Font_Arial_Bold_18_004f[52] = {
    _______X, _XXXXXXX, X_X_____, ________, 
    ____XXXX, XXXXXXXX, XXXXX_X_, ________, 
    ___XXXXX, XXXXXXXX, XXXXXXX_, ________, 
    _X_XXXXX, ________, _X_XXXXX, ________, 
    _XXXXX__, ________, ___X_XXX, X_______, 
    _XXXX_X_, ________, ____XXXX, X_______, 
    _XXXX___, ________, _____XXX, X_______, 
    _XXXX_X_, ________, ____XXXX, X_______, 
    _XXXXX__, ________, ___X_XXX, X_______, 
    _X_XXXXX, __X_____, _X_XXXXX, ________, 
    ___XXXXX, XXXXXXXX, XXXXXXX_, ________, 
    ____XXXX, XXXXXXXX, XXXXX_X_, ________, 
    _______X, _XXXXXXX, XX______, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0050[39] = {
    _X_XXXXX, XXXXXXXX, __X_____, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXX__, _______X, _XXXX___, 
    _X_XXX__, _______X, _XXXX___, 
    _X_XXXXX, XXXXXXXX, XXXXX___, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXXX, XXXXXXXX, __X_____, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0051[56] = {
    _______X, _XXXXXXX, XX______, ________, 
    ____XXXX, XXXXXXXX, XXXXX_X_, ________, 
    ___XXXXX, XXXXXXXX, XXXXXXX_, ________, 
    _X_XXXXX, ________, _X_XXXXX, ________, 
    _XXXXX__, ________, ___X_XXX, X_______, 
    _XXXX_X_, ________, ____XXXX, X_______, 
    _XXXX___, ________, _____XXX, X_______, 
    _XXXX_X_, _____X__, ___X_XXX, X_______, 
    _XXXXX__, ____XXXX, XX_XXXXX, X_______, 
    _X_XXXXX, ______XX, XXXXXXXX, ________, 
    ___XXXXX, XXXXXXXX, XXXXXXX_, ________, 
    ____XXXX, XXXXXXXX, XXXXXXX_, X_______, 
    _______X, _XXXXXXX, XX_X_XXX, X_X_____, 
    ________, ________, ______XX, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0052[52] = {
    _X_XXXXX, XXXXXXXX, XX______, ________, 
    _X_XXXXX, XXXXXXXX, XXXXX___, ________, 
    _X_XXXXX, XXXXXXXX, XXXXXX__, ________, 
    _X_XXX__, ________, _XXXXX__, ________, 
    _X_XXX__, ________, _XXXXX__, ________, 
    _X_XXXXX, XXXXXXXX, XXXXX_X_, ________, 
    _X_XXXXX, XXXXXXXX, XXXX____, ________, 
    _X_XXXXX, XXXXXXXX, X_______, ________, 
    _X_XXX__, ___X_XXX, XX______, ________, 
    _X_XXX__, _____X_X, XXX_X___, ________, 
    _X_XXX__, _______X, XXXXX___, ________, 
    _X_XXX__, ________, _XXXXXX_, ________, 
    _X_XXX__, ________, __XXXXX_, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0053[39] = {
    _____X_X, XXXXXX__, X_______, 
    ___XXXXX, XXXXXXXX, XX______, 
    _X_XXXXX, XXXXXXXX, XXX_X___, 
    _X_XXXX_, ______XX, XXX_X___, 
    _X_XXXX_, X_______, ________, 
    __XXXXXX, XXXXX_X_, ________, 
    ____XXXX, XXXXXXXX, XX______, 
    ________, XX_XXXXX, XXXX____, 
    ________, ______XX, _XXXX___, 
    _XXXXX__, _______X, _XXXX___, 
    _XXXXXXX, XXXXXXXX, XXXXX___, 
    __XXXXXX, XXXXXXXX, XXX_X___, 
    _____X_X, XXXXXXXX, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0054[39] = {
    _X_XXXXX, XXXXXXXX, XXXXX_X_, 
    _X_XXXXX, XXXXXXXX, XXXXX_X_, 
    _X_XXXXX, XXXXXXXX, XXXXX_X_, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
    ________, _XXXXX__, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0055[39] = {
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXX__, ________, _XXXX_X_, 
    _X_XXXX_, ________, _XXXX_X_, 
    __XXXXXX, _______X, _XXXX_X_, 
    ___XXXXX, XXXXXXXX, XXXXX___, 
    ___X_XXX, XXXXXXXX, XXXX____, 
    ______XX, _XXXXXXX, __X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0056[52] = {
    _XXXXXX_, ________, ___XXXXX, ________, 
    __XXXXX_, X_______, __XXXXX_, X_______, 
    ___XXXXX, ________, _X_XXXX_, ________, 
    ___XXXXX, X_______, _XXXXX__, ________, 
    ____XXXX, X_______, XXXXX_X_, ________, 
    _____XXX, X_X_____, XXXXX___, ________, 
    _____XXX, XXX____X, XXXX____, ________, 
    ______XX, XXX____X, XXX_X___, ________, 
    _______X, XXX_X_XX, XXX_____, ________, 
    _______X, XXXX_XXX, XX______, ________, 
    ________, XXXXXXXX, X_X_____, ________, 
    ________, _XXXXXXX, X_______, ________, 
    ________, _XXXXXXX, ________, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0057[65] = {
    _XXXXX__, _______X, XXXXX___, _____X_X, XXX_____, 
    _X_XXXX_, ______XX, XXXXX_X_, _____XXX, XX______, 
    __XXXXX_, _____X_X, XXXXXX__, _____XXX, X_X_____, 
    ___XXXX_, X____XXX, XXXXXXX_, ____XXXX, X_______, 
    ___XXXXX, _____XXX, X_XXXXX_, X___XXXX, X_______, 
    ___X_XXX, X___XXXX, X__XXXX_, X__X_XXX, ________, 
    ____XXXX, X__X_XXX, ___X_XXX, ___XXXX_, X_______, 
    _____XXX, X__XXXX_, X___XXXX, X__XXXX_, ________, 
    _____XXX, XX_XXXX_, _____XXX, XX_XXXX_, ________, 
    _____X_X, XXXXXX__, _____X_X, XXXXXX__, ________, 
    ______XX, XXXXX_X_, ______XX, XXXXX_X_, ________, 
    ______XX, XXXXX___, _______X, XXXXX_X_, ________, 
    _______X, XXXXX___, _______X, XXXXX___, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0058[52] = {
    ___XXXXX, X_______, _XXXXXX_, ________, 
    ____XXXX, X_X_____, XXXXX_X_, ________, 
    _____XXX, XXX____X, XXXX____, ________, 
    _______X, XXXX_XXX, XXX_____, ________, 
    ________, XXXXXXXX, X_X_____, ________, 
    ________, _XXXXXXX, X_______, ________, 
    ________, _X_XXXXX, ________, ________, 
    ________, XXXXXXXX, X_X_____, ________, 
    _______X, XXXXXXXX, XXX_____, ________, 
    _____X_X, XXX_X_XX, XXXX____, ________, 
    ____XXXX, XX_____X, _XXXX_X_, ________, 
    ___XXXXX, X_______, _XXXXXX_, ________, 
    _X_XXXX_, X_______, __XXXXX_, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0059[52] = {
    _X_XXXX_, X_______, __XXXXX_, X_______, 
    ___XXXXX, X_______, _XXXXXX_, ________, 
    ____XXXX, X_X_____, XXXXX_X_, ________, 
    _____X_X, XXX____X, XXXX____, ________, 
    _______X, XXXX_X_X, XXX_____, ________, 
    ________, XXXXXXXX, X_X_____, ________, 
    ________, _XXXXXXX, ________, ________, 
    ________, __XXXXX_, X_______, ________, 
    ________, ___XXXX_, ________, ________, 
    ________, ___XXXX_, ________, ________, 
    ________, ___XXXX_, ________, ________, 
    ________, ___XXXX_, ________, ________, 
    ________, ___XXXX_, ________, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_005a[39] = {
    ___XXXXX, XXXXXXXX, XXXXX_X_, 
    ___XXXXX, XXXXXXXX, XXXXX_X_, 
    ___XXXXX, XXXXXXXX, XXXXX___, 
    ________, _____XXX, XXX_X___, 
    ________, ___X_XXX, X_X_____, 
    ________, _X_XXXXX, ________, 
    ________, XXXXXXX_, ________, 
    _______X, XXXXX___, ________, 
    _____XXX, XXX_X___, ________, 
    ___X_XXX, XX______, ________, 
    __XXXXXX, XXXXXXXX, XXXXXX__, 
    _X_XXXXX, XXXXXXXX, XXXXXX__, 
    _X_XXXXX, XXXXXXXX, XXXXXX__, 
};

gui_const uint8_t Font_Arial_Bold_18_005b[34] = {
    _X_XXXXX, XXX_____, 
    _X_XXXXX, XXX_____, 
    _X_XXXXX, XXX_____, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXX__, ________, 
    _X_XXXXX, XXX_____, 
    _X_XXXXX, XXX_____, 
    _X_XXXXX, XXX_____, 
};

gui_const uint8_t Font_Arial_Bold_18_005c[26] = {
    _XXXX___, ________, 
    _X_XX___, ________, 
    __XXX_X_, ________, 
    ___XXX__, ________, 
    ___XXXX_, ________, 
    ___X_XX_, ________, 
    ____XXX_, X_______, 
    _____XXX, ________, 
    _____XXX, X_______, 
    _____X_X, X_______, 
    ______XX, X_X_____, 
    _______X, X_X_____, 
    _______X, XX______, 
};

gui_const uint8_t Font_Arial_Bold_18_005d[34] = {
    _XXXXXXX, XX______, 
    _XXXXXXX, XX______, 
    _XXXXXXX, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _XXXXXXX, XX______, 
    _XXXXXXX, XX______, 
    _XXXXXXX, XX______, 
};

gui_const uint8_t Font_Arial_Bold_18_005e[21] = {
    _______X, XXX_X___, ________, 
    ______XX, XXXXX___, ________, 
    _____XXX, XXXXX_X_, ________, 
    ____XXXX, X_XXXXX_, ________, 
    ___XXXX_, X__XXXX_, ________, 
    __XXXXX_, ___X_XXX, ________, 
    _XXXXX__, _____XXX, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_005f[6] = {
    _XXXXXXX, XXXXXXXX, XXXXX___, 
    _XXXXXXX, XXXXXXXX, XXXXX___, 
};

gui_const uint8_t Font_Arial_Bold_18_0060[3] = {
    _XXXX_X_, 
    __XXXX__, 
    ___X_XX_, 
};

gui_const uint8_t Font_Arial_Bold_18_0061[30] = {
    ____XXXX, XXXXX_X_, ________, 
    __XXXXXX, XXXXXXX_, X_______, 
    _XXXX_X_, ___XXXXX, ________, 
    ________, XX_XXXXX, ________, 
    __XXXXXX, XXXXXXXX, ________, 
    _XXXXXX_, X__X_XXX, ________, 
    XXXXX___, ___X_XXX, ________, 
    XXXXX_X_, __XXXXXX, ________, 
    _XXXXXXX, XXXXXXXX, ________, 
    ___X_XXX, X_X__XXX, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0062[39] = {
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_X_, XXXXXX__, X_______, 
    _XXXXXXX, XXXXXXXX, X_X_____, 
    _XXXXXX_, X____XXX, XXX_____, 
    _XXXXX__, ______XX, XXX_____, 
    _XXXX_X_, _______X, XXX_____, 
    _XXXX_X_, _______X, XXX_____, 
    _XXXXX__, ______XX, XXX_____, 
    _XXXXXX_, X____XXX, XXX_____, 
    _XXXXXXX, XXXXXXXX, X_X_____, 
    _XXXX_X_, XXXXXX__, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0063[30] = {
    _____X_X, XXXXX_X_, ________, 
    ___XXXXX, XXXXXXX_, X_______, 
    _X_XXXX_, ___X_XXX, X_______, 
    _XXXX_X_, ____XX__, X_______, 
    _XXXX___, ________, ________, 
    _XXXX___, ________, ________, 
    _XXXX_X_, _____X__, X_______, 
    _X_XXXX_, ___X_XXX, X_X_____, 
    ___XXXXX, XXXXXXXX, ________, 
    _____X_X, XXXXX_X_, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0064[39] = {
    ________, ______XX, XXX_____, 
    ________, ______XX, XXX_____, 
    ________, ______XX, XXX_____, 
    ____XX_X, XXX_X_XX, XXX_____, 
    __XXXXXX, XXXXXXXX, XXX_____, 
    _XXXXXX_, ____XXXX, XXX_____, 
    _XXXX_X_, _____X_X, XXX_____, 
    _XXXX___, ______XX, XXX_____, 
    _XXXX___, ______XX, XXX_____, 
    _XXXX_X_, _____X_X, XXX_____, 
    _X_XXXX_, ____XXXX, XXX_____, 
    ___XXXXX, XXXXXXXX, XXX_____, 
    _____X_X, XXX_X_XX, XXX_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0065[30] = {
    ____XX_X, XXXX____, ________, 
    __XXXXXX, XXXXXXX_, ________, 
    _XXXXX__, ___X_XXX, ________, 
    _XXXX___, ____XXXX, X_______, 
    XXXXXXXX, XXXXXXXX, X_______, 
    XXXXXXXX, XXXXXXXX, X_______, 
    _XXXX___, ________, ________, 
    _XXXXX__, ___X_XXX, X_______, 
    __XXXXXX, XXXXXXX_, X_______, 
    ____XX_X, XXXX__X_, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0066[26] = {
    ______XX, XXXXX_X_, 
    _____XXX, XXXXX_X_, 
    ____XXXX, X_______, 
    _X_XXXXX, XXXXX___, 
    _X_XXXXX, XXXXX___, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0067[42] = {
    ____XX_X, XXX_X_XX, XXX_____, 
    __XXXXXX, XXXXXX_X, XXX_____, 
    _XXXXXX_, ____XXXX, XXX_____, 
    _XXXX_X_, _____X_X, XXX_____, 
    _XXXX___, ______XX, XXX_____, 
    _XXXX___, ______XX, XXX_____, 
    _XXXX_X_, _____X_X, XXX_____, 
    _X_XXXX_, ____XXXX, XXX_____, 
    ___XXXXX, XXXXXX_X, XXX_____, 
    ____XXXX, XXX_X_XX, XXX_____, 
    ________, ______XX, XXX_____, 
    _XXXXXX_, _____XXX, XX______, 
    __XXXXXX, XXXXXXXX, X_X_____, 
    ____XX_X, XXXXXX__, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0068[39] = {
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, ________, ________, 
    _X_XXX__, _X_XXXX_, X_______, 
    _X_XXXXX, XXXXXXXX, X_X_____, 
    _X_XXXXX, _____XXX, XXX_____, 
    _X_XXXX_, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0069[13] = {
    _X_XXX__, 
    _X_XXX__, 
    ________, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
};

gui_const uint8_t Font_Arial_Bold_18_006a[34] = {
    _____X_X, XX______, 
    _____X_X, XX______, 
    ________, ________, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____X_X, XX______, 
    _____XXX, X_X_____, 
    __XXXXXX, X_X_____, 
    _X_XXXX_, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_006b[39] = {
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ___X_XXX, X_______, 
    _XXXX_X_, _X_XXXX_, X_______, 
    _XXXX_XX, _XXXX_X_, ________, 
    _XXXXXXX, XXX_X___, ________, 
    _XXXXXXX, XXXXX___, ________, 
    _XXXXXXX, _XXXX_X_, ________, 
    _XXXXX__, _X_XXXX_, ________, 
    _XXXX_X_, ___XXXX_, X_______, 
    _XXXX_X_, ____XXXX, X_______, 
    _XXXX_X_, _____XXX, X_X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_006c[13] = {
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
    _X_XXX__, 
};

gui_const uint8_t Font_Arial_Bold_18_006d[40] = {
    _XXXX_X_, XXXXXX__, ___X_XXX, X_X_____, 
    _XXXXXXX, XXXXXXXX, _XXXXXXX, XXX_X___, 
    _XXXXXX_, ___X_XXX, XX_____X, XXXX____, 
    _XXXXX__, ____XXXX, X_X____X, _XXX____, 
    _XXXX_X_, _____XXX, X______X, _XXX____, 
    _XXXX_X_, _____XXX, X______X, _XXX____, 
    _XXXX_X_, _____XXX, X______X, _XXX____, 
    _XXXX_X_, _____XXX, X______X, _XXX____, 
    _XXXX_X_, _____XXX, X______X, _XXX____, 
    _XXXX_X_, _____XXX, X______X, _XXX____, 
};

gui_const uint8_t Font_Arial_Bold_18_006e[30] = {
    _X_XXX__, _X_XXXXX, ________, 
    _X_XXXXX, XXXXXXXX, XX______, 
    _X_XXXXX, _____XXX, XXX_____, 
    _X_XXXX_, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
    _X_XXX__, ______XX, XXX_____, 
};

gui_const uint8_t Font_Arial_Bold_18_006f[30] = {
    _____X_X, XXXXXX__, ________, 
    ___XXXXX, XXXXXXXX, X_______, 
    _X_XXXX_, _____XXX, XX______, 
    _XXXX_X_, ______XX, XXX_____, 
    _XXXX___, _______X, XXX_____, 
    _XXXX___, _______X, XXX_____, 
    _XXXX_X_, ______XX, XXX_____, 
    _X_XXXX_, _____XXX, XX______, 
    ___XXXXX, XXXXXXXX, X_______, 
    _____X_X, XXXXXX__, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0070[42] = {
    _XXXX_X_, XXXXXX__, X_______, 
    _XXXXXXX, XXXXXXXX, X_X_____, 
    _XXXXXX_, X____XXX, XXX_____, 
    _XXXXX__, ______XX, XXX_____, 
    _XXXX_X_, _______X, XXX_____, 
    _XXXX_X_, _______X, XXX_____, 
    _XXXXX__, ______XX, XXX_____, 
    _XXXXXX_, X____XXX, XXX_____, 
    _XXXXXXX, XXXXXXXX, X_X_____, 
    _XXXX_X_, XXXXXX__, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ________, ________, 
    _XXXX_X_, ________, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0071[42] = {
    _____X_X, XXX_X_XX, XXX_____, 
    ___XXXXX, XXXXXXXX, XXX_____, 
    _X_XXXX_, X____XXX, XXX_____, 
    _XXXXX__, _____X_X, XXX_____, 
    _XXXX_X_, ______XX, XXX_____, 
    _XXXX_X_, ______XX, XXX_____, 
    _X_XXX__, _____X_X, XXX_____, 
    __XXXXX_, X___XXXX, XXX_____, 
    ___XXXXX, XXXXXXXX, XXX_____, 
    _____X_X, XXX_X_XX, XXX_____, 
    ________, ______XX, XXX_____, 
    ________, ______XX, XXX_____, 
    ________, ______XX, XXX_____, 
    ________, ______XX, XXX_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0072[20] = {
    _XXXX_XX, _XXXX___, 
    _XXXXXXX, XXXXX___, 
    _XXXXXX_, ________, 
    _XXXXX__, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
    _XXXX_X_, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0073[30] = {
    ___X_XXX, XXXX____, ________, 
    _X_XXXXX, XXXXXXX_, ________, 
    _XXXX_X_, ___XXXXX, ________, 
    _XXXXXX_, X_______, ________, 
    __XXXXXX, XXXX____, ________, 
    _____X_X, XXXXXXX_, X_______, 
    ________, ___X_XXX, X_______, 
    XXXXX_X_, ___X_XXX, X_______, 
    _X_XXXXX, XXXXXXXX, ________, 
    ____XXXX, XXXX__X_, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0074[26] = {
    ______XX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    _X_XXXXX, XXXX____, 
    _X_XXXXX, XXXX____, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, X_______, 
    ____XXXX, XXXX____, 
    _____X_X, XXXX____, 
};

gui_const uint8_t Font_Arial_Bold_18_0075[30] = {
    _XXXX_X_, _____X_X, XX______, 
    _XXXX_X_, _____X_X, XX______, 
    _XXXX_X_, _____X_X, XX______, 
    _XXXX_X_, _____X_X, XX______, 
    _XXXX_X_, _____X_X, XX______, 
    _XXXX_X_, _____X_X, XX______, 
    _XXXX_X_, _____XXX, XX______, 
    _XXXXXX_, ____XXXX, XX______, 
    __XXXXXX, XXXXXXXX, XX______, 
    ____XXXX, XX__XX_X, XX______, 
};

gui_const uint8_t Font_Arial_Bold_18_0076[30] = {
    _X_XXX__, _______X, XXX_X___, 
    __XXXXX_, ______XX, XXX_____, 
    ___XXXX_, X____X_X, XX______, 
    ___X_XXX, _____XXX, X_X_____, 
    _____XXX, X___XXXX, X_______, 
    _____XXX, X_XX_XXX, ________, 
    ______XX, XX_XXXX_, ________, 
    _______X, XXXXXXX_, ________, 
    _______X, _XXXX_X_, ________, 
    ________, XXXXX___, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_0077[40] = {
    _X_XXX__, _____XXX, X_X_____, XXXXX___, 
    __XXXXX_, ____XXXX, XX_____X, _XXX____, 
    ___XXXX_, ___X_XXX, XXX____X, XXX_X___, 
    ___XXXX_, X__XXXXX, XXX____X, XXX_____, 
    ___X_XXX, ___XXXXX, _XX_X_XX, XXX_____, 
    ____XXXX, X_XXXX__, XXXX_X_X, XX______, 
    _____XXX, XXXXX_X_, _XXXXXXX, X_X_____, 
    _____X_X, XXXXX___, _X_XXXXX, X_______, 
    ______XX, XXXXX___, __XXXXXX, ________, 
    _______X, XXXX____, __XXXXX_, X_______, 
};

gui_const uint8_t Font_Arial_Bold_18_0078[30] = {
    _XXXXX__, ____XXXX, X_______, 
    __XXXXX_, ___XXXX_, X_______, 
    ___XXXXX, _XXXXXX_, ________, 
    ____XXXX, XXXXX___, ________, 
    _____X_X, XXXX____, ________, 
    _____XXX, XXXXX___, ________, 
    ____XXXX, XXXXX_X_, ________, 
    ___XXXX_, XX_XXXX_, ________, 
    _XXXXXX_, ___XXXXX, ________, 
    XXXXX___, ____XXXX, X_X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_0079[42] = {
    _XXXX_X_, _______X, XXX_X___, 
    __XXXXX_, ______XX, XXX_____, 
    ___XXXX_, _____X_X, XX______, 
    ___XXXX_, X____XXX, X_X_____, 
    ____XXXX, X___XXXX, X_______, 
    _____XXX, X__X_XXX, ________, 
    _____X_X, XX_XXXX_, X_______, 
    ______XX, XXXXXXX_, ________, 
    _______X, XXXXXX__, ________, 
    _______X, _XXXX_X_, ________, 
    _______X, _XXXX___, ________, 
    _______X, XXXX____, ________, 
    ___XXXXX, XXX_____, ________, 
    ___XXXXX, __X_____, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_007a[30] = {
    _XXXXXXX, XXXXXXX_, ________, 
    _XXXXXXX, XXXXXXX_, ________, 
    ________, XXXXXXX_, ________, 
    _______X, XXXXX___, ________, 
    _____XXX, XXX_X___, ________, 
    ___X_XXX, XX______, ________, 
    __XXXXXX, X_______, ________, 
    _XXXXXX_, ________, ________, 
    XXXXXXXX, XXXXXXXX, ________, 
    XXXXXXXX, XXXXXXXX, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_007b[34] = {
    ______XX, XXX_X___, 
    _____XXX, XXX_X___, 
    ____XXXX, X_______, 
    ____XXXX, ________, 
    ___X_XXX, ________, 
    ___X_XXX, ________, 
    ___X_XX_, X_______, 
    ___XXXX_, X_______, 
    XXXXXX__, ________, 
    XXXXXX__, ________, 
    ___XXXX_, X_______, 
    ___X_XXX, ________, 
    ___X_XXX, ________, 
    ____XXXX, ________, 
    ____XXXX, ________, 
    ____XXXX, XXX_X___, 
    ______XX, XXX_X___, 
};

gui_const uint8_t Font_Arial_Bold_18_007c[17] = {
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
    XXX_X___, 
};

gui_const uint8_t Font_Arial_Bold_18_007d[34] = {
    XXXXX_X_, ________, 
    XXXXXXX_, ________, 
    ___XXXX_, X_______, 
    ___X_XX_, X_______, 
    ___X_XXX, ________, 
    ___X_XXX, ________, 
    ____XXXX, ________, 
    ____XXXX, X_______, 
    _____X_X, XXX_X___, 
    _____X_X, XXX_X___, 
    ____XXXX, X_______, 
    ___X_XXX, ________, 
    ___X_XXX, ________, 
    ___X_XX_, X_______, 
    ___X_XX_, X_______, 
    XXXXXXX_, X_______, 
    XXXXX_X_, ________, 
};

gui_const uint8_t Font_Arial_Bold_18_007e[12] = {
    _X_XXXXX, __X_____, _X______, 
    XXXXXXXX, XXXXXXXX, XXX_____, 
    XXXXXXXX, XXXXXXXX, XXX_____, 
    X_X_____, XX_XXXXX, __X_____, 
};

gui_const uint8_t Font_Arial_Bold_18_007f[1] = {
    ________, 
};


gui_const gui_font_char_t Arial_Bold_18_CharTable[] = {
{   0,    1,  0,    0,    6, Font_Arial_Bold_18_0020},
{   3,   13,  0,    1,    0, Font_Arial_Bold_18_0021},
{   8,    5,  0,    1,    0, Font_Arial_Bold_18_0022},
{  11,   13,  0,    1,    0, Font_Arial_Bold_18_0023},
{   9,   16,  0,    0,    0, Font_Arial_Bold_18_0024},
{  15,   14,  0,    1,    0, Font_Arial_Bold_18_0025},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_0026},
{   3,    5,  0,    1,    0, Font_Arial_Bold_18_0027},
{   5,   17,  0,    1,    0, Font_Arial_Bold_18_0028},
{   5,   17,  0,    1,    0, Font_Arial_Bold_18_0029},
{   8,    6,  0,    1,    0, Font_Arial_Bold_18_002a},
{  10,    9,  0,    3,    0, Font_Arial_Bold_18_002b},
{   4,    6,  0,   11,    0, Font_Arial_Bold_18_002c},
{   6,    3,  0,    8,    0, Font_Arial_Bold_18_002d},
{   4,    3,  0,   11,    0, Font_Arial_Bold_18_002e},
{   6,   13,  0,    1,    0, Font_Arial_Bold_18_002f},
{   9,   13,  0,    1,    0, Font_Arial_Bold_18_0030},
{   6,   13,  0,    1,    0, Font_Arial_Bold_18_0031},
{   9,   13,  0,    1,    0, Font_Arial_Bold_18_0032},
{   9,   13,  0,    1,    0, Font_Arial_Bold_18_0033},
{  11,   13,  0,    1,    0, Font_Arial_Bold_18_0034},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_0035},
{   9,   13,  0,    1,    0, Font_Arial_Bold_18_0036},
{   9,   13,  0,    1,    0, Font_Arial_Bold_18_0037},
{   9,   13,  0,    1,    0, Font_Arial_Bold_18_0038},
{   9,   13,  0,    1,    0, Font_Arial_Bold_18_0039},
{   3,   10,  0,    4,    0, Font_Arial_Bold_18_003a},
{   3,   13,  0,    4,    0, Font_Arial_Bold_18_003b},
{  10,   10,  0,    3,    0, Font_Arial_Bold_18_003c},
{  10,    8,  0,    4,    0, Font_Arial_Bold_18_003d},
{  10,   10,  0,    3,    0, Font_Arial_Bold_18_003e},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_003f},
{  17,   17,  0,    1,    0, Font_Arial_Bold_18_0040},
{  14,   13,  0,    1,    0, Font_Arial_Bold_18_0041},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_0042},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_0043},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_0044},
{  11,   13,  0,    1,    0, Font_Arial_Bold_18_0045},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_0046},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_0047},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_0048},
{   4,   13,  0,    1,    0, Font_Arial_Bold_18_0049},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_004a},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_004b},
{  11,   13,  0,    1,    0, Font_Arial_Bold_18_004c},
{  14,   13,  0,    1,    0, Font_Arial_Bold_18_004d},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_004e},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_004f},
{  11,   13,  0,    1,    0, Font_Arial_Bold_18_0050},
{  14,   14,  0,    1,    0, Font_Arial_Bold_18_0051},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_0052},
{  11,   13,  0,    1,    0, Font_Arial_Bold_18_0053},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_0054},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_0055},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_0056},
{  18,   13,  0,    1,    0, Font_Arial_Bold_18_0057},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_0058},
{  13,   13,  0,    1,    0, Font_Arial_Bold_18_0059},
{  12,   13,  0,    1,    0, Font_Arial_Bold_18_005a},
{   6,   17,  0,    1,    0, Font_Arial_Bold_18_005b},
{   6,   13,  0,    1,    0, Font_Arial_Bold_18_005c},
{   6,   17,  0,    1,    0, Font_Arial_Bold_18_005d},
{   9,    7,  0,    1,    0, Font_Arial_Bold_18_005e},
{  11,    2,  0,   16,    0, Font_Arial_Bold_18_005f},
{   4,    3,  0,    1,    0, Font_Arial_Bold_18_0060},
{   9,   10,  0,    4,    0, Font_Arial_Bold_18_0061},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_0062},
{  10,   10,  0,    4,    0, Font_Arial_Bold_18_0063},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_0064},
{   9,   10,  0,    4,    0, Font_Arial_Bold_18_0065},
{   8,   13,  0,    1,    0, Font_Arial_Bold_18_0066},
{  10,   14,  0,    4,    0, Font_Arial_Bold_18_0067},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_0068},
{   4,   13,  0,    1,    0, Font_Arial_Bold_18_0069},
{   6,   17,  0,    1,    0, Font_Arial_Bold_18_006a},
{  10,   13,  0,    1,    0, Font_Arial_Bold_18_006b},
{   4,   13,  0,    1,    0, Font_Arial_Bold_18_006c},
{  15,   10,  0,    4,    0, Font_Arial_Bold_18_006d},
{  10,   10,  0,    4,    0, Font_Arial_Bold_18_006e},
{  10,   10,  0,    4,    0, Font_Arial_Bold_18_006f},
{  10,   14,  0,    4,    0, Font_Arial_Bold_18_0070},
{  10,   14,  0,    4,    0, Font_Arial_Bold_18_0071},
{   7,   10,  0,    4,    0, Font_Arial_Bold_18_0072},
{   9,   10,  0,    4,    0, Font_Arial_Bold_18_0073},
{   7,   13,  0,    1,    0, Font_Arial_Bold_18_0074},
{  10,   10,  0,    4,    0, Font_Arial_Bold_18_0075},
{  11,   10,  0,    4,    0, Font_Arial_Bold_18_0076},
{  15,   10,  0,    4,    0, Font_Arial_Bold_18_0077},
{  10,   10,  0,    4,    0, Font_Arial_Bold_18_0078},
{  11,   14,  0,    4,    0, Font_Arial_Bold_18_0079},
{   9,   10,  0,    4,    0, Font_Arial_Bold_18_007a},
{   7,   17,  0,    1,    0, Font_Arial_Bold_18_007b},
{   3,   17,  0,    1,    0, Font_Arial_Bold_18_007c},
{   7,   17,  0,    1,    0, Font_Arial_Bold_18_007d},
{  10,    4,  0,    5,    0, Font_Arial_Bold_18_007e},
{   0,    1,  0,    0,    6, Font_Arial_Bold_18_007f},
};

gui_const gui_font_t GUI_Font_Arial_Bold_18 = {
    _GT("Arial Bold"),
    18,
    0x20,
    0x7f,
    GUI_FLAG_FONT_AA,
    Arial_Bold_18_CharTable
};
