#include "gui/gui.h"

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0020[1] = {
    ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0021[18] = {
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _X______, 
    ________, 
    _X______, 
    XXX_____, 
    _X______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0022[7] = {
    XX___X__, 
    XX__XX__, 
    XX__XX__, 
    XX__XX__, 
    XX__XX__, 
    XX__XX__, 
    XX__XX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0023[51] = {
    _______X, X_____XX, ________, 
    _______X, X_____XX, ________, 
    ______XX, ______XX, ________, 
    ______XX, _____XX_, ________, 
    __XXXXXX, XXXXXXXX, XX______, 
    _XXXXXXX, XXXXXXXX, XX______, 
    _____XX_, ____XXX_, ________, 
    _____XX_, ____XX__, ________, 
    _____XX_, ____XX__, ________, 
    ____XX__, ____XX__, ________, 
    ____XX__, ___XX___, ________, 
    XXXXXXXX, XXXXXXXX, X_______, 
    _XXXXXXX, XXXXXXXX, X_______, 
    ___XX___, __XXX___, ________, 
    ___XX___, __XX____, ________, 
    __XXX___, __XX____, ________, 
    __XX____, __XX____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0024[44] = {
    _____XX_, ________, 
    _____XX_, ________, 
    _____XXX, X_______, 
    ___XXXXX, XXX_____, 
    __XXXXX_, _XX_____, 
    _XXX_XX_, ________, 
    _XX__XX_, ________, 
    _XX__XX_, ________, 
    _XXXXXX_, ________, 
    __XXXXXX, XX______, 
    _____XXX, XXX_____, 
    _____XX_, _XXX____, 
    _____XX_, __XX____, 
    _____XX_, __XX____, 
    _____XX_, __XX____, 
    XX___XX_, _XXX____, 
    XXXXXXXX, XXX_____, 
    _XXXXXXX, XX______, 
    ____XXX_, ________, 
    _____XX_, ________, 
    _____XX_, ________, 
    _____XX_, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0025[36] = {
    __XX____, ________, 
    XXXXX___, __X_____, 
    XX__XX__, _XX_____, 
    X___XX__, _XX_____, 
    XX__XX__, XX______, 
    XXXXXX__, XX______, 
    _XXX___X, X_______, 
    _______X, X_______, 
    ______XX, ________, 
    ______XX, ________, 
    _____XX_, ________, 
    _____XX_, __XXX___, 
    ____XX__, _XXXXXX_, 
    ____XX__, XX___XX_, 
    ___XX___, XX___XX_, 
    ___XX___, XX___XX_, 
    ___XX___, XXXXXXX_, 
    __XX____, _XXXXX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0026[36] = {
    ______XX, ________, 
    _____XXX, X_______, 
    ____XXX_, XX______, 
    ____XX__, XX______, 
    ____XX_X, X_______, 
    ____XXXX, X_______, 
    _____XXX, ________, 
    ___XXXX_, ________, 
    __XXX_XX, ___X____, 
    _XXX__XX, __XX____, 
    XXX____X, X_XX____, 
    XX_____X, X_XX____, 
    XX______, XXX_____, 
    XX______, XXX_____, 
    XX______, XXX_____, 
    _XXX_XXX, X_XX____, 
    __XXXXXX, __XX____, 
    ________, ___XX___, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0027[6] = {
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0028[22] = {
    ____XX__, 
    ___XXX__, 
    ___XX___, 
    __XX____, 
    __XX____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    XXX_____, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XXX_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    _XXX____, 
    __XX____, 
    ___XX___, 
    ____XX__, 
    _____X__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0029[22] = {
    XX______, 
    _XX_____, 
    __XX____, 
    __XXX___, 
    ___XX___, 
    ___XXX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ___XXX__, 
    ___XX___, 
    __XXX___, 
    _XXX____, 
    XXX_____, 
    _X______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_002a[18] = {
    ___XX___, ________, 
    ___XX___, ________, 
    XX_XX_XX, X_______, 
    XXXXXXXX, X_______, 
    __XXXX__, ________, 
    __XXXXX_, ________, 
    _XXX_XXX, ________, 
    XXX___XX, ________, 
    _______X, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_002b[16] = {
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    XXXXXXXX, X_______, 
    XXXXXXXX, X_______, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_002c[6] = {
    __X_____, 
    _XX_____, 
    _XX_____, 
    _XX_____, 
    XX______, 
    _X______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_002d[2] = {
    _XXXXXX_, 
    XXXXXXX_, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_002e[3] = {
    XX______, 
    XX______, 
    XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_002f[36] = {
    ________, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    ______XX, ________, 
    ______XX, ________, 
    _____XXX, ________, 
    _____XX_, ________, 
    ____XXX_, ________, 
    ____XX__, ________, 
    ___XXX__, ________, 
    ___XX___, ________, 
    __XXX___, ________, 
    __XX____, ________, 
    _XXX____, ________, 
    _XX_____, ________, 
    XXX_____, ________, 
    XX______, ________, 
    XX______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0030[34] = {
    ____XXX_, ________, 
    __XXXXXX, X_______, 
    __XXX__X, XX______, 
    _XX_____, XXX_____, 
    XXX_____, _XX_____, 
    XX______, _XX_____, 
    XX______, _XXX____, 
    XX______, __XX____, 
    XX______, __XX____, 
    XX______, _XXX____, 
    XX______, _XXX____, 
    XX______, _XX_____, 
    XX______, _XX_____, 
    XXX_____, XXX_____, 
    _XX_____, XX______, 
    _XXXXXXX, XX______, 
    __XXXXXX, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0031[17] = {
    ___XX___, 
    __XXX___, 
    _XXXX___, 
    XXXXX___, 
    X__XX___, 
    ___XX___, 
    ___XX___, 
    __XXX___, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    XXXXXXX_, 
    XXXXXX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0032[32] = {
    __XXXXXX, ________, 
    _XXXXXXX, X_______, 
    XXX____X, XX______, 
    X______X, XX______, 
    _______X, XX______, 
    _______X, X_______, 
    ______XX, X_______, 
    ____XXXX, ________, 
    ___XXXX_, ________, 
    __XXX___, ________, 
    _XXX____, ________, 
    XXX_____, ________, 
    XX______, ________, 
    XX______, ________, 
    XXXXXXXX, XX______, 
    XXXXXXXX, XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0033[34] = {
    _XXXXXXX, ________, 
    XXXXXXXX, X_______, 
    XX_____X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    ______XX, X_______, 
    ___XXXXX, ________, 
    __XXXXX_, ________, 
    _____XXX, X_______, 
    _______X, X_______, 
    _______X, XX______, 
    _______X, XX______, 
    X______X, XX______, 
    XX_____X, X_______, 
    XXXXXXXX, X_______, 
    _XXXXXXX, ________, 
    ____X___, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0034[34] = {
    _______X, X_______, 
    ______XX, X_______, 
    _____XXX, X_______, 
    _____XXX, X_______, 
    ____XX_X, X_______, 
    ___XXX_X, X_______, 
    ___XX__X, X_______, 
    __XXX__X, X_______, 
    _XXX___X, X_______, 
    _XX____X, X_______, 
    XXXXXXXX, XXX_____, 
    XXXXXXXX, XXXX____, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0035[36] = {
    ________, _X______, 
    _XXXXXXX, XXX_____, 
    _XXXXXXX, XX______, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_XXXX, X_______, 
    _XXXXXXX, XX______, 
    _XXXX___, XXX_____, 
    _XXX____, _XX_____, 
    _XX_____, _XX_____, 
    ________, _XX_____, 
    ________, _XX_____, 
    ________, _XX_____, 
    ________, _XX_____, 
    XX______, XXX_____, 
    _XXX__XX, XX______, 
    _XXXXXXX, X_______, 
    ___XXXX_, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0036[36] = {
    ______X_, ________, 
    _____XXX, ________, 
    ____XXX_, ________, 
    ___XXX__, ________, 
    __XXX___, ________, 
    __XX____, ________, 
    _XX_____, ________, 
    _XXXXXXX, X_______, 
    XXXXXXXX, XX______, 
    XXX_____, XX______, 
    XX______, _XX_____, 
    XX______, _XX_____, 
    XX______, _XX_____, 
    XXX_____, _XX_____, 
    _XX_____, XX______, 
    _XXX___X, XX______, 
    __XXXXXX, X_______, 
    ____XXX_, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0037[34] = {
    XXXXXXXX, XXXX____, 
    XXXXXXXX, XXXX____, 
    ________, XXX_____, 
    _______X, XX______, 
    _______X, X_______, 
    ______XX, X_______, 
    ______XX, ________, 
    _____XXX, ________, 
    _____XX_, ________, 
    ____XXX_, ________, 
    ____XX__, ________, 
    ____XX__, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    __XXX___, ________, 
    __XX____, ________, 
    __XX____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0038[34] = {
    ___XXXXX, X_______, 
    __XXXXXX, XX______, 
    _XX_____, XX______, 
    _XX_____, XX______, 
    _XX_____, XX______, 
    _XX____X, XX______, 
    __XXXXXX, X_______, 
    ___XXXXX, X_______, 
    __XXX_XX, XX______, 
    _XX_____, XXX_____, 
    XXX_____, _XX_____, 
    XX______, _XX_____, 
    XX______, _XX_____, 
    XXX_____, XXX_____, 
    _XXX___X, XX______, 
    __XXXXXX, X_______, 
    ____XXX_, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0039[34] = {
    __XXXXXX, X_______, 
    _XXXX__X, XX______, 
    _XX_____, XXX_____, 
    XX______, _XX_____, 
    XX______, _XX_____, 
    XX______, _XX_____, 
    XXX_____, _XX_____, 
    _XX_____, XXX_____, 
    _XXXXXXX, XXX_____, 
    __XXXXXX, _XX_____, 
    ________, XX______, 
    _______X, XX______, 
    _______X, X_______, 
    _____XXX, X_______, 
    ___XXXXX, ________, 
    _XXXXX__, ________, 
    _XXX____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_003a[11] = {
    XX______, 
    XX______, 
    XX______, 
    ________, 
    ________, 
    ________, 
    ________, 
    _X______, 
    XX______, 
    XX______, 
    _X______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_003b[14] = {
    _XX_____, 
    _XX_____, 
    _XX_____, 
    ________, 
    ________, 
    ________, 
    ________, 
    ________, 
    ________, 
    ________, 
    _XX_____, 
    XXX_____, 
    XX______, 
    XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_003c[9] = {
    ____XXX_, 
    ___XXX__, 
    ___XX___, 
    _XXX____, 
    XXX_____, 
    _XXX____, 
    ___XX___, 
    ____XX__, 
    _____X__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_003d[8] = {
    XXXXXXXX, 
    XXXXXXXX, 
    ________, 
    ________, 
    ________, 
    ________, 
    XXXXXXXX, 
    XXXXXXXX, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_003e[10] = {
    XX______, 
    XXX_____, 
    _XXX____, 
    __XXX___, 
    ___XXXX_, 
    ____XXX_, 
    __XXXX__, 
    _XXX____, 
    XXX_____, 
    XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_003f[34] = {
    __XXXX__, ________, 
    XXXXXXX_, ________, 
    XXX__XXX, ________, 
    X_____XX, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    ______XX, X_______, 
    _____XXX, ________, 
    ____XXX_, ________, 
    __XXXX__, ________, 
    __XXX___, ________, 
    __XX____, ________, 
    ________, ________, 
    __X_____, ________, 
    _XXX____, ________, 
    __X_____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0040[57] = {
    ________, X_______, ________, 
    _____XXX, XXXXX___, ________, 
    ___XXXXX, XXXXXXX_, ________, 
    __XXXX__, ____XXXX, ________, 
    __XX____, ______XX, X_______, 
    _XXX___X, XX_____X, X_______, 
    _XX___XX, XX_____X, XX______, 
    XXX__XXX, ________, XX______, 
    XXX__XX_, __X_____, XX______, 
    XX__XX__, _XXX____, XX______, 
    XX__XX__, _XX____X, XX______, 
    XX___XXX, XXXXXXXX, X_______, 
    XXX__XXX, X_XXXXXX, ________, 
    _XX_____, ____XX__, ________, 
    _XXX____, ________, ________, 
    __XX____, ________, ________, 
    ___XXX__, _____X__, ________, 
    ____XXXX, XXXXXXX_, ________, 
    _____XXX, XXXXXX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0041[32] = {
    ________, _X______, 
    ________, XX______, 
    _______X, XXX_____, 
    ______XX, XXX_____, 
    ______XX, _XX_____, 
    _____XXX, _XX_____, 
    _____XX_, _XX_____, 
    ____XX__, _XXX____, 
    ___XXX__, XXXX____, 
    ___XXXXX, XXXX____, 
    __XXXXXX, X_XX____, 
    __XX____, __XX____, 
    _XXX____, __XXX___, 
    _XX_____, ___XX___, 
    _XX_____, ___XX___, 
    XXX_____, ___XXX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0042[36] = {
    _XXXXX__, ________, 
    _XXXXXXX, ________, 
    _XX__XXX, X_______, 
    XXX____X, XX______, 
    XXX_____, XX______, 
    XXX_____, XX______, 
    XX_____X, XX______, 
    XX_____X, X_______, 
    XXX_XXXX, X_______, 
    XXXXXXXX, ________, 
    XXXXXXXX, XX______, 
    XX_____X, XXX_____, 
    XX______, _XX_____, 
    XX______, XXX_____, 
    XX_____X, XX______, 
    XXXXXXXX, X_______, 
    XXXXXXXX, ________, 
    _X______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0043[32] = {
    ______XX, XXXX____, 
    _____XXX, XXXX____, 
    ____XXX_, _XXX____, 
    ___XXX__, __XX____, 
    __XXX___, ________, 
    _XXX____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XXX_____, _XX_____, 
    _XXX___X, XXX_____, 
    _XXXXXXX, XX______, 
    ___XXXXX, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0044[36] = {
    _X______, ________, 
    XXXX____, ________, 
    XXXXXXX_, ________, 
    XX_XXXXX, ________, 
    XX___XXX, XX______, 
    XX_____X, XXX_____, 
    XX______, _XX_____, 
    XX______, _XXX____, 
    XX______, __XX____, 
    XX______, __XXX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, __XXX___, 
    XX______, __XX____, 
    XX______, _XXX____, 
    XXX_____, XXX_____, 
    XXXXXXXX, XX______, 
    __XXXXXX, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0045[36] = {
    XXXXXXXX, XXX_____, 
    XXXXXXXX, XXX_____, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX___XXX, XX______, 
    XXXXXXXX, XX______, 
    XXXXXXXX, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XXXXXXXX, XX______, 
    _XXXXXXX, XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0046[36] = {
    _XXXXXXX, X_______, 
    XXXXXXXX, XXX_____, 
    XXXX____, XXX_____, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XXXXXXXX, XX______, 
    XXXXXXXX, XX______, 
    XXX_____, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0047[36] = {
    ______XX, X_______, 
    ____XXXX, XXX_____, 
    ___XXXX_, XXXX____, 
    ___XX___, ________, 
    __XXX___, ________, 
    _XXX____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    XXX_____, __XXX___, 
    XX___XXX, XXXXXX__, 
    XX__XXXX, XXXXX___, 
    XX__XX__, __XXX___, 
    XX______, __XX____, 
    XX______, _XXX____, 
    XXX_____, XXX_____, 
    _XXX__XX, XX______, 
    _XXXXXXX, X_______, 
    ___XXXX_, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0048[36] = {
    _X______, ____X___, 
    XX______, ____XX__, 
    XX______, ___XXX__, 
    XX______, ___XX___, 
    XX______, ___XXX__, 
    XX______, ___XXX__, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX____XX, XXXXX___, 
    XXXXXXXX, XXXXX___, 
    XXXXXX__, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    X_______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0049[32] = {
    XXXXXXXX, XX______, 
    XXXXXXXX, XX______, 
    ____XX__, XX______, 
    ____XX__, ________, 
    ____XX__, ________, 
    ___XXX__, ________, 
    ___XXX__, ________, 
    ___XXX__, ________, 
    ___XXX__, ________, 
    ___XXX__, ________, 
    ___XXX__, ________, 
    ____XX__, ________, 
    ____XX__, ________, 
    ___XXX__, ________, 
    XXXXXXXX, XX______, 
    XXXXXXXX, XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_004a[34] = {
    ___XXXXX, XXXXX___, 
    ___XXXXX, XXXXX___, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XXX____X, X_______, 
    _XXX__XX, ________, 
    __XXXXXX, ________, 
    ___XXXX_, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_004b[34] = {
    _XX_____, _XX_____, 
    _XX_____, XX______, 
    _XX____X, XX______, 
    _XX___XX, X_______, 
    _XX__XXX, ________, 
    _XX_XXX_, ________, 
    XX_XXX__, ________, 
    XXXXX___, ________, 
    XXXX____, ________, 
    XXXXX___, ________, 
    XXXXXX__, ________, 
    XXX_XXX_, ________, 
    XXX__XXX, ________, 
    XXX___XX, X_______, 
    XXX____X, XXX_____, 
    XXX_____, XXX_____, 
    _X______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_004c[36] = {
    _X______, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    XXX_____, ________, 
    XXX_____, ________, 
    XXX_____, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, _X______, 
    XX___XXX, XXX_____, 
    XXXXXXXX, XX______, 
    _XXXXXX_, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_004d[51] = {
    ____XX__, ____XX__, ________, 
    ___XXX__, ____XXX_, ________, 
    ___XXX__, ___XXXX_, ________, 
    ___XXXX_, ___XXXX_, ________, 
    ___XXXX_, ___XXXX_, ________, 
    __XXXXX_, ___XXXX_, ________, 
    __XX_XX_, __XXXXX_, ________, 
    __XX_XX_, __XX__XX, ________, 
    __XX_XXX, __XX__XX, ________, 
    _XXX__XX, _XXX__XX, ________, 
    _XX___XX, _XX___XX, ________, 
    _XX___XX, _XX___XX, ________, 
    _XX___XX, XXX___XX, X_______, 
    XXX____X, XX_____X, X_______, 
    XXX____X, XX_____X, X_______, 
    XX_____X, XX_____X, XX______, 
    _X______, ________, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_004e[36] = {
    _X______, ________, 
    XXX_____, _____XX_, 
    XXXX____, _____XX_, 
    XXXX____, _____XX_, 
    _XXXX___, _____XXX, 
    _XXXXX__, _____XXX, 
    _XX_XXX_, _____XXX, 
    _XX__XX_, _____XXX, 
    _XX___XX, _____XXX, 
    _XX___XX, X____XXX, 
    _XX____X, XX___XXX, 
    _XX_____, XXX__XXX, 
    _XX_____, _XXX__XX, 
    _XX_____, __XXX_XX, 
    _XX_____, ___XXXXX, 
    XXX_____, ____XXX_, 
    XXX_____, _____XX_, 
    _X______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_004f[34] = {
    _____XXX, XXXXX___, 
    ____XXXX, XXXXXX__, 
    ___XXX__, ____XXX_, 
    __XXX___, _____XX_, 
    __XX____, _____XX_, 
    _XXX____, _____XXX, 
    _XX_____, _____XXX, 
    XXX_____, _____XXX, 
    XXX_____, _____XX_, 
    XX______, _____XX_, 
    XX______, _____XX_, 
    XXX_____, ____XXX_, 
    _XX_____, ___XXX__, 
    _XXX____, __XXX___, 
    __XXXXXX, XXXXX___, 
    ___XXXXX, XXX_____, 
    ______XX, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0050[34] = {
    _XXXXX__, ________, 
    _XXXXXXX, ________, 
    _X____XX, X_______, 
    XX_____X, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    XX_____X, X_______, 
    XX___XXX, X_______, 
    XXXXXXX_, ________, 
    XXXXX___, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0051[63] = {
    _____XXX, XXXXX___, ________, 
    ____XXXX, XXXXXX__, ________, 
    ___XXX__, ____XXX_, ________, 
    __XXX___, _____XXX, ________, 
    _XXX____, ______XX, ________, 
    XXX_____, ______XX, X_______, 
    XX______, _______X, X_______, 
    XX______, _______X, X_______, 
    XX______, _______X, X_______, 
    XX______, _______X, X_______, 
    XX______, _______X, X_______, 
    XXX_____, XX____XX, X_______, 
    _XX_____, XX____XX, ________, 
    _XXX____, XXX_XXXX, ________, 
    __XXXX__, _XXXXXX_, ________, 
    ___XXXXX, XXXXXX__, ________, 
    _____XXX, XXXXXXX_, ________, 
    ________, _____XXX, ________, 
    ________, ______XX, X_______, 
    ________, _______X, XX______, 
    ________, ________, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0052[32] = {
    _XXXXXX_, ________, 
    XXXXXXXX, X_______, 
    _XX___XX, XX______, 
    _XX_____, XXX_____, 
    _XX_____, _XX_____, 
    _XX_____, _XX_____, 
    _XX_____, _XX_____, 
    XXX_____, XXX_____, 
    XXX___XX, XX______, 
    XXXXXXXX, X_______, 
    XXXXXXX_, ________, 
    XX__XXXX, X_______, 
    XX____XX, XX______, 
    XXX_____, XXX_____, 
    XXX_____, _XXX____, 
    XXX_____, __XX____, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0053[34] = {
    ______XX, XX______, 
    ____XXXX, XXXX____, 
    ___XXXX_, __XX____, 
    __XXX___, ________, 
    __XX____, ________, 
    __XX____, ________, 
    __XXXXX_, ________, 
    ___XXXXX, XXX_____, 
    _______X, XXXX____, 
    ________, __XXX___, 
    ________, ___XX___, 
    ________, ___XX___, 
    _X______, ___XX___, 
    XXX_____, __XXX___, 
    _XXXX__X, XXXX____, 
    __XXXXXX, XX______, 
    _____XXX, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0054[32] = {
    XXXXXXXX, XXXXXX__, 
    XXXXXXXX, XXXXXXX_, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, X_______, 
    ______XX, X_______, 
    ______XX, X_______, 
    ______XX, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0055[32] = {
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, ___XX___, 
    XX______, __XXX___, 
    XX______, __XXX___, 
    XX______, __XX____, 
    XX______, __XX____, 
    XXX_____, _XXX____, 
    _XXX____, _XX_____, 
    _XXXXX_X, XXX_____, 
    ___XXXXX, XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0056[34] = {
    XX______, __XX____, 
    XX______, _XXX____, 
    XX______, _XX_____, 
    XX______, _XX_____, 
    XXX_____, XXX_____, 
    _XX_____, XX______, 
    _XX_____, XX______, 
    _XXX___X, X_______, 
    __XX___X, X_______, 
    __XX__XX, X_______, 
    __XX__XX, ________, 
    __XXX_XX, ________, 
    ___XXXXX, ________, 
    ___XXXX_, ________, 
    ___XXXX_, ________, 
    ____XX__, ________, 
    ____XX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0057[51] = {
    XX______, _XX_____, __XXX___, 
    XX______, XXX_____, __XX____, 
    XX______, XXXX____, __XX____, 
    XXX_____, XXXX____, _XXX____, 
    _XX____X, XXXX____, _XX_____, 
    _XX____X, XXXX____, _XX_____, 
    _XXX___X, X_XX____, XX______, 
    __XX__XX, X_XX____, XX______, 
    __XX__XX, X_XX____, XX______, 
    __XX__XX, ___XX__X, X_______, 
    __XX_XXX, ___XX__X, X_______, 
    ___XXXX_, ___XX_XX, ________, 
    ___XXXX_, ___XX_XX, ________, 
    ___XXXX_, ___XXXXX, ________, 
    ___XXX__, ____XXX_, ________, 
    ___XXX__, ____XXX_, ________, 
    ____X___, ____XX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0058[34] = {
    XXX_____, ____XX__, 
    _XXX____, ___XXX__, 
    __XX____, __XXX___, 
    __XXX___, __XX____, 
    ___XXX__, _XXX____, 
    ____XXX_, XXX_____, 
    _____XXX, XX______, 
    ______XX, X_______, 
    ______XX, X_______, 
    _____XXX, XX______, 
    ____XXX_, XX______, 
    ___XXX__, XXX_____, 
    __XXX___, _XXX____, 
    _XXX____, __XX____, 
    XXX_____, __XXX___, 
    XX______, ___XXX__, 
    X_______, ____XX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0059[34] = {
    XXX_____, ___XX___, 
    _XX_____, ___XX___, 
    _XXX____, __XX____, 
    __XX____, __XX____, 
    ___XX___, _XXX____, 
    ___XXX__, _XX_____, 
    ____XX__, XXX_____, 
    ____XXX_, XX______, 
    _____XX_, XX______, 
    _____XXX, X_______, 
    ______XX, X_______, 
    ______XX, X_______, 
    ______XX, ________, 
    _____XXX, ________, 
    _____XX_, ________, 
    ____XX__, ________, 
    ____XX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_005a[34] = {
    XXXXXXXX, XXXXXX__, 
    XXXXXXXX, XXXXXX__, 
    ________, _XXXX___, 
    ________, XXX_____, 
    _______X, XX______, 
    ______XX, X_______, 
    ______XX, ________, 
    _____XX_, ________, 
    ____XXX_, ________, 
    ___XXX__, ________, 
    ___XX___, ________, 
    __XXX___, ________, 
    _XXX____, ________, 
    _XX_____, ________, 
    XXX___XX, XXXXX___, 
    XXXXXXXX, XXXXXX__, 
    _XXX____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_005b[20] = {
    XXXXX___, 
    XXXXX___, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XXXXX___, 
    XXXXXX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_005c[34] = {
    XX______, ________, 
    XXX_____, ________, 
    _XX_____, ________, 
    _XXX____, ________, 
    __XX____, ________, 
    __XX____, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ____XX__, ________, 
    ____XX__, ________, 
    ____XX__, ________, 
    _____XX_, ________, 
    _____XX_, ________, 
    _____XXX, ________, 
    ______XX, ________, 
    ______XX, X_______, 
    _______X, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_005d[20] = {
    XXXXX___, 
    _XXXX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ____X___, 
    ____X___, 
    ____X___, 
    ____X___, 
    ____XX__, 
    ____XX__, 
    XXXXXX__, 
    XXXXXX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_005e[12] = {
    ____X___, ________, 
    ___XXX__, ________, 
    __XXXXX_, ________, 
    _XXX_XXX, ________, 
    XXX___XX, X_______, 
    XX_____X, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_005f[4] = {
    XXXXXXXX, XXXXXX__, 
    XXXXXXXX, XXXXXX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0060[5] = {
    X_______, 
    XX______, 
    _XX_____, 
    _XXX____, 
    __XX____, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0061[24] = {
    ___XXXXX, ________, 
    _XXXXXXX, X_______, 
    _XX____X, X_______, 
    XXX____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XXX___XX, X_______, 
    _XXXXXXX, XX______, 
    ___XX___, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0062[34] = {
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XXXXXXXX, ________, 
    XXXXXXXX, X_______, 
    XXX____X, X_______, 
    XX______, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    XX_____X, X_______, 
    XXXXXXXX, X_______, 
    XXXXXXXX, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0063[24] = {
    ___XXXXX, ________, 
    __XXXXXX, X_______, 
    _XXX____, X_______, 
    _XX_____, ________, 
    XXX_____, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XXX_____, X_______, 
    _XXX__XX, X_______, 
    __XXXXXX, X_______, 
    ____XX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0064[34] = {
    ________, _XX_____, 
    ________, _XX_____, 
    ________, _XX_____, 
    ________, _XX_____, 
    ________, _XX_____, 
    ________, _XX_____, 
    ___XXXXX, _X______, 
    __XXXXXX, XX______, 
    _XX_____, XX______, 
    XXX_____, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    XX______, XX______, 
    _XX_____, XX______, 
    _XXXXXXX, XXX_____, 
    __XXXXXX, _XX_____, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0065[22] = {
    ___XXXXX, ________, 
    __XXXXXX, X_______, 
    _XX_____, XX______, 
    XXX___XX, X_______, 
    XX__XXXX, ________, 
    XXXXXXX_, ________, 
    XXXXX___, ________, 
    XX______, ________, 
    XXX_____, _XX_____, 
    _XXXX_XX, XX______, 
    __XXXXXX, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0066[38] = {
    _____XXX, X_______, 
    ____XXXX, X_______, 
    ___XXX__, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    _XXXXXXX, X_______, 
    XXXXXXXX, X_______, 
    _X_XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    __XXX___, ________, 
    ___X____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0067[34] = {
    ___XXXXX, ________, 
    __XXXXXX, XX______, 
    _XX_____, XX______, 
    XX______, XX______, 
    XX_____X, XX______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX____XX, X_______, 
    _XXXXXXX, X_______, 
    _XXXXX_X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    _______X, X_______, 
    ______XX, ________, 
    XXXXXXXX, ________, 
    XXXXXX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0068[36] = {
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX__XXXX, ________, 
    XX_XXXXX, X_______, 
    XXXX___X, X_______, 
    XXX____X, X_______, 
    XXX____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, XX______, 
    ________, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0069[16] = {
    XXX_____, 
    XXX_____, 
    ________, 
    ________, 
    ________, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_006a[22] = {
    ____XX__, 
    ____XX__, 
    ________, 
    ________, 
    ________, 
    ____XX__, 
    ____XX__, 
    ____XXX_, 
    ____XXX_, 
    ____XXX_, 
    ____XXX_, 
    _____XX_, 
    _____XX_, 
    _____XX_, 
    _____XX_, 
    _____XX_, 
    _____XX_, 
    X____XX_, 
    XX___XX_, 
    XXX__XX_, 
    _XXXXXX_, 
    __XXXX__, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_006b[34] = {
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX_____X, X_______, 
    XX____XX, X_______, 
    XX___XXX, ________, 
    XX__XXX_, ________, 
    XX_XXX__, ________, 
    XXXXXX__, ________, 
    XXXXXX__, ________, 
    XXX__XX_, ________, 
    XX___XXX, ________, 
    XX____XX, X_______, 
    XX_____X, X_______, 
    XX_____X, XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_006c[17] = {
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_006d[26] = {
    _X______, ________, 
    XXX_XXXX, _XXXX___, 
    XX_XXXXX, XXXXXX__, 
    XX_XX_XX, XX__XX__, 
    XXXX__XX, ____XX__, 
    _XX___XX, ____XX__, 
    _XX___XX, ____XXX_, 
    XXX___XX, X____XX_, 
    XX_____X, X____XX_, 
    XX_____X, X____XX_, 
    XX_____X, X____XX_, 
    XXX____X, X____XX_, 
    _X_____X, X____XX_, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_006e[26] = {
    _X______, ________, 
    _XX_XXXX, X_______, 
    _XXXXXXX, X_______, 
    _XXXX__X, X_______, 
    _XXX___X, X_______, 
    _XX____X, X_______, 
    XXX____X, X_______, 
    XXX____X, X_______, 
    XXX____X, X_______, 
    XX_____X, XX______, 
    XXX_____, XX______, 
    XXX_____, XX______, 
    _X______, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_006f[24] = {
    ___XXXX_, ________, 
    __XXXXXX, ________, 
    _XXX__XX, X_______, 
    XXX____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XXX____X, X_______, 
    _XXXXXXX, ________, 
    __XXXXX_, ________, 
    ___XXX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0070[36] = {
    _X______, ________, 
    XX__XXXX, ________, 
    XXXXXXXX, X_______, 
    XXXX___X, X_______, 
    XXX____X, XX______, 
    _XX_____, XX______, 
    _XX_____, XX______, 
    _XX_____, XX______, 
    _XX____X, XX______, 
    _XX____X, X_______, 
    _XXXXXXX, X_______, 
    _XXXXXXX, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
    _XX_____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0071[34] = {
    ___XXXXX, X_______, 
    _XXXX__X, X_______, 
    _XX____X, X_______, 
    XXX____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX____XX, X_______, 
    _XXXXXXX, X_______, 
    __XXXXXX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
    ______XX, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0072[24] = {
    _X__XXXX, X_______, 
    _XXXXXXX, X_______, 
    _XXX___X, X_______, 
    XXX____X, X_______, 
    XXX_____, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    XX______, ________, 
    _X______, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0073[26] = {
    ______XX, X_______, 
    ___XXXXX, XX______, 
    __XXXX__, XX______, 
    _XXX____, X_______, 
    _XX_____, ________, 
    __XXXXX_, ________, 
    ___XXXXX, ________, 
    ______XX, X_______, 
    _______X, X_______, 
    _X_____X, X_______, 
    XXXXXXXX, X_______, 
    _XXXXXXX, X_______, 
    ___XXX__, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0074[32] = {
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    XXXXXXXX, X_______, 
    XXXXXXXX, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    ____X___, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0075[24] = {
    XXX____X, X_______, 
    XXX____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    _XX____X, X_______, 
    _XXXXXXX, X_______, 
    _XXXXXXX, X_______, 
    ____X___, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0076[22] = {
    XX_____X, X_______, 
    XX_____X, X_______, 
    XX_____X, X_______, 
    _XX___XX, ________, 
    _XX___XX, ________, 
    _XXX_XXX, ________, 
    __XX_XX_, ________, 
    __XX_XX_, ________, 
    ___XXX__, ________, 
    ___XXX__, ________, 
    ___XX___, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0077[24] = {
    XX____XX, ___XX___, 
    XX___XXX, ___XX___, 
    XX___XXX, ___XX___, 
    XX___XXX, ___XX___, 
    XX__XX_X, __XXX___, 
    XXX_XX_X, X_XX____, 
    _XX_X__X, X_XX____, 
    _XXXX__X, X_XX____, 
    _XXXX__X, XXX_____, 
    _XXX___X, XXX_____, 
    __XX____, XXX_____, 
    __X_____, XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0078[24] = {
    _X______, __X_____, 
    _XX_____, _XX_____, 
    __XX____, XXX_____, 
    __XXX__X, XX______, 
    ___XXXXX, X_______, 
    ____XXXX, ________, 
    ____XXX_, ________, 
    ___XXXXX, ________, 
    __XXX_XX, X_______, 
    _XXX___X, X_______, 
    XXX_____, XX______, 
    XX______, XXX_____, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_0079[34] = {
    XX______, _XX_____, 
    XXX_____, XXX_____, 
    _XX_____, XX______, 
    _XXX___X, XX______, 
    __XX___X, X_______, 
    __XXX__X, X_______, 
    ___XX_XX, X_______, 
    ___XXXXX, ________, 
    ____XXXX, ________, 
    ____XXX_, ________, 
    ____XXX_, ________, 
    ____XX__, ________, 
    ___XXX__, ________, 
    ___XX___, ________, 
    ___XX___, ________, 
    __XXX___, ________, 
    __XX____, ________, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_007a[24] = {
    _XXXXXXX, XX______, 
    _XXXXXXX, XX______, 
    _______X, X_______, 
    ______XX, ________, 
    _____XXX, ________, 
    _____XX_, ________, 
    ____XX__, ________, 
    ___XXX__, ________, 
    __XXX___, ________, 
    _XXXXXXX, X_______, 
    XXXXXXXX, XX______, 
    XXXX____, X_______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_007b[21] = {
    ___XXXX_, 
    ___XXXX_, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    _XXX____, 
    XXX_____, 
    XXX_____, 
    _XXX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XX____, 
    __XXX___, 
    ___XXXX_, 
    ____XXX_, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_007c[22] = {
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
    XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_007d[21] = {
    XXXX____, 
    _XXXX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ___XX___, 
    ____XX__, 
    ____XXX_, 
    ____XXX_, 
    ____XX__, 
    ___XX___, 
    ____XX__, 
    ____XX__, 
    ____XX__, 
    ___XX___, 
    ___XX___, 
    XXXXX___, 
    XXXX____, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_007e[10] = {
    __XXX___, __X_____, 
    _XXXXX__, _XX_____, 
    XXX__XX_, _XX_____, 
    XX___XXX, XXX_____, 
    _______X, XX______, 
};

gui_const uint8_t Font_Comic_Sans_MS_Regular_size_12_007f[1] = {
    ________, 
};


gui_const gui_font_char_t CharTable[] = {
    {   7,    1,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_0020},
    {   3,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0021},
    {   6,    7,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0022},
    {  18,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0023},
    {  12,   22,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_0024},
    {  15,   18,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_0025},
    {  13,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0026},
    {   2,    6,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_0027},
    {   6,   22,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0028},
    {   6,   22,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0029},
    {   9,    9,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_002a},
    {   9,    8,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_002b},
    {   3,    6,  0,   16,    1, Font_Comic_Sans_MS_Regular_size_12_002c},
    {   7,    2,  0,   11,    1, Font_Comic_Sans_MS_Regular_size_12_002d},
    {   2,    3,  0,   16,    1, Font_Comic_Sans_MS_Regular_size_12_002e},
    {   9,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_002f},
    {  12,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0030},
    {   7,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0031},
    {  10,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0032},
    {  10,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0033},
    {  12,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0034},
    {  11,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0035},
    {  11,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0036},
    {  12,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0037},
    {  11,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0038},
    {  11,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0039},
    {   2,   11,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_003a},
    {   3,   14,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_003b},
    {   7,    9,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_003c},
    {   8,    8,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_003d},
    {   7,   10,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_003e},
    {   9,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_003f},
    {  18,   19,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_0040},
    {  14,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0041},
    {  11,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0042},
    {  12,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0043},
    {  13,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0044},
    {  11,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0045},
    {  11,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0046},
    {  14,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0047},
    {  14,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0048},
    {  10,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0049},
    {  13,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_004a},
    {  11,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_004b},
    {  11,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_004c},
    {  18,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_004d},
    {  16,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_004e},
    {  16,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_004f},
    {  10,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0050},
    {  18,   21,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0051},
    {  12,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0052},
    {  13,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0053},
    {  15,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0054},
    {  13,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0055},
    {  12,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0056},
    {  21,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0057},
    {  14,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0058},
    {  13,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0059},
    {  14,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_005a},
    {   6,   20,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_005b},
    {   9,   17,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_005c},
    {   6,   20,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_005d},
    {   9,    6,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_005e},
    {  14,    2,  0,   20,    1, Font_Comic_Sans_MS_Regular_size_12_005f},
    {   4,    5,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_0060},
    {  10,   12,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0061},
    {  10,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0062},
    {   9,   12,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0063},
    {  11,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0064},
    {  11,   11,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0065},
    {   9,   19,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0066},
    {  10,   17,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0067},
    {  10,   18,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_0068},
    {   3,   16,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_0069},
    {   7,   22,  0,    2,    1, Font_Comic_Sans_MS_Regular_size_12_006a},
    {  10,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_006b},
    {   2,   17,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_006c},
    {  15,   13,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_006d},
    {  10,   13,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_006e},
    {   9,   12,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_006f},
    {  10,   18,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_0070},
    {   9,   17,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0071},
    {   9,   12,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0072},
    {  10,   13,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_0073},
    {   9,   16,  0,    3,    1, Font_Comic_Sans_MS_Regular_size_12_0074},
    {   9,   12,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0075},
    {   9,   11,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0076},
    {  13,   12,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0077},
    {  11,   12,  0,    6,    1, Font_Comic_Sans_MS_Regular_size_12_0078},
    {  11,   17,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_0079},
    {  10,   12,  0,    7,    1, Font_Comic_Sans_MS_Regular_size_12_007a},
    {   7,   21,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_007b},
    {   2,   22,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_007c},
    {   7,   21,  0,    1,    1, Font_Comic_Sans_MS_Regular_size_12_007d},
    {  11,    5,  0,    8,    1, Font_Comic_Sans_MS_Regular_size_12_007e},
    {   7,    1,  0,    0,    1, Font_Comic_Sans_MS_Regular_size_12_007f},
};

gui_const gui_font_t GUI_Font_Comic_Sans_MS_Regular_22 = {
    _GT("Comic Sans MS Regular"),
    22,
    0x20,
    0x7f,
    0,
    CharTable
};
